In [1]:
import numpy as np
import xarray as xr

In [30]:
data = xr.DataArray(np.random.randn(2, 3), dims=("x", "y"), coords={"x": [1, 2]})

In [31]:
data

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.36505243, -1.07590038,  0.21777217],
       [-0.28283764,  0.29247285,  0.63216379]])
Coordinates:
  * x        (x) int64 1 2
Dimensions without coordinates: y

In [32]:
np.issubdtype(data.dtype, np.integer)

False

In [25]:
list(zip(data.dims, data.shape))

[('x', 2), ('y', 3)]

In [26]:
data.dims

('x', 'y')

In [27]:
data.data.tolist()

[[-0.9789793999990964, 1.1005806976450159, -1.2336112484802253],
 [-1.1783837621247004, 0.7113789040878121, -0.985583380874692]]

In [28]:
data.coords["x"].data.tolist()

['a', 'b']

In [35]:
data.sel(x=2)

<xarray.DataArray (y: 3)>
array([-0.28283764,  0.29247285,  0.63216379])
Coordinates:
    x        int64 2
Dimensions without coordinates: y

In [40]:
data.reindex(y=[1, 2, 3], x=data.coords["x"])

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.36505243, -1.07590038,  0.21777217],
       [-0.28283764,  0.29247285,  0.63216379]])
Coordinates:
  * x        (x) int64 1 2
  * y        (y) int64 1 2 3

In [44]:
data.transpose("y", "x")

<xarray.DataArray (y: 3, x: 2)>
array([[ 0.36505243, -0.28283764],
       [-1.07590038,  0.29247285],
       [ 0.21777217,  0.63216379]])
Coordinates:
  * x        (x) int64 1 2
Dimensions without coordinates: y

In [50]:
data.coords["x"].data.tolist()

[1, 2]

In [51]:
data.sizes

Frozen({'x': 2, 'y': 3})